name: .NET Core

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4.2.2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
          dotnet-version: 6.0.300
    - name: Build with dotnet
      run: dotnet build --configuration Release
